spring:
  application:
    id: 62345112312312
  profiles: prod
micro:
  server:
    host: cache
    port: 8060
    name: cache
    tokens: 10000
  pool:
    maxTotal: 30  #池中的最大连接数
    minIdle: 0    #最少的空闲连接数
    maxIdle: 50    #最多的空闲连接数
    maxWaitMillis: 1    #当连接池资源耗尽时,调用者最大阻塞的时间,超时时抛出异常 单位:毫秒数
    lifo: true    #连接池存放池化对象方式,true放在空闲队列最前面,false放在空闲队列最后
    blockWhenExhausted: true  #连接耗尽时是否阻塞,默认为true
grpc:
  server:
    host: cache
    port: 8060