spring:
  application:
    id: 5334536  #当前节点id
    redundant_id: 7668769  #冗余节点id
  profiles: prod

  # 邮箱配置
  mail:
    # 配置 SMTP 服务器地址
    host: smtp.263.net
    # 发送者邮箱
    username: devel@tscc.com.cn
    # 配置密码，如果不走 SSL 加密，密码就可以
    # 如果走 SSL 加密 ，而是申请到的授权码
    password: Kf@1234
    # SMTP	smtp.263.net	25	465
    port: 25
    # 默认的邮件编码为UTF-8
    default-encoding: UTF-8
    # 配置SSL 加密工厂
#    properties:
#      mail:
#        smtp:
#          socketFactoryClass: javax.net.ssl.SSLSocketFactory
#        #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
#        debug: true


grpc:
  server:
    open: 1
    host: monitor
    port: 6869
    name: monitor
    #tokens: 6000

monitor:
  patterns:
    #    - model: JK
    #      process: prototype
    #      casenum: 2
    - model: PVSS
      process: prototype
      casenum: 4
  issue_queue: queue-monitor-issue   #监控任务下发队列
  identity: master  #节点标识(主从)
  #  send_queue_name: queue-monitor-monitor1-slave #投递队列
  #  monitor_queue_name: queue-monitor-monitor1-master #监控队列
  send_queue_name: queue-monitor-send-monitor64 #投递队列
  monitor_queue_name: queue-monitor-monitor64-master #监控队列
driver:
  plugins:
    - model: PVSS
      device_id: pvss-device-1  #设备ID
      model_host: 10.0.1.222
      model_port: 6000
      #model_url: http://10.0.2.151:18090/data
      #model_url: http://100.1.2.12:18090/data  # 吉林项目采集地址
      model_url: http://124.164.242.71:18090/data  #  晋城项目外网采集地址
      #      model_url: http://10.0.2.63:18091/data
      issue_url: http://10.0.2.151:18090/setdata
      model_count: 1
      model_status: 0
      pointls_sign: monitor100-pvss-0-5000   #对应点表标识
      cycle_time: 10000    #循环采集周期(ms)
      colony_policy: 1    #集群策略
    - model: PVSS
      device_id: pvss-device-2  #设备ID
      model_host: 10.0.1.222
      model_port: 6000
      #model_url: http://10.0.2.151:18090/data
      #model_url: http://100.1.2.12:18090/data  # 吉林项目采集地址
      model_url: http://124.164.242.71:18090/data  #  晋城项目外网采集地址
      #      model_url: http://10.0.2.63:18091/data
      issue_url: http://10.0.2.151:18090/setdata
      model_count: 1
      model_status: 0
      pointls_sign: monitor100-pvss-5001-10000   #对应点表标识
      cycle_time: 10000    #循环采集周期(ms)
      colony_policy: 1    #集群策略
#    - model: PVSS
#      device_id: boanrnosgfsg  #设备ID
#      model_host: 10.0.1.111
#      model_port: 5000
#      model_url: http://10.0.1.101:5000/pvss/famg/id
#      model_count: 1
#      model_status: 0
#      pointls_sign: fsgsefsg_001   #对应点表标识
#      cycle_time: 8000    #循环采集周期(ms)
#      colony_policy: 1    #集群策略
#    - model: PVSS
#      model_host: 10.0.1.121
#      model_port: 5000
#      model_url:
#      model_count: 2
#      model_status: 0
#    - model: JK
#      device_id: cn=Jk  #设备ID
#      model_host: 10.0.2.66
#      model_port: 5002
#      model_url:
#      issue_url:
#      model_count: 1
#      model_status: 0
#      pointls_sign: monitor10_JK-0:50000   #对应点表标识
#      cycle_time: 8000    #循环采集周期(ms)
#      colony_policy: 1    #集群策略
#    - model: JK
#      model_host: 10.0.1.2
#      model_port: 6000
#      model_url:
#      model_count: 2
#      model_status: 0
#    - model: JK
#      model_host: 10.0.1.3
#      model_port: 6000
#      model_url:
#      model_count: 3
#      model_status: 0